function clearTraceView( fig )
%CLEARTRACEVIEW Summary of this function goes here
%   Detailed explanation goes here
    handles = guidata(fig);
    
    datafile = handles.datafile;
    if datafile.length == -1
        % no .dat is loaded to be removed
        return;
    end

    % remove channelIds
    for i=1:size(datafile.channelIds,1)
        delete(datafile.channelIds(i));
    end
    
    cla(handles.axes1);
    handles.datafile = struct(  'numberOfChannels',128,...
                    'resolution',2,...
                    'samplingRate',20000,...
                    'file',-1,...
                    'length',-1,...
                    'channelLines',[],...
                    'activeChannels',[],...
                    'channelRangeString','',...
                    'channelIds',[],...
                    'bufferStart',0,...
                    'bufferEnd',0,...
                    'buffer',[],... % 128*#datapoints
                    'loadStart',5000,... % if center of window is smaller than this
                    'loadEnd',15000,... % if center of window is larger than this
                    'bufferSize',-1,... % the size of the buffer
                    'maxBufferSize',20000,... % in datapoints
                    'dataWindow',[0,0],...
                    'windowSize',-1,...
                    'maxWindowSize',10000,... % has to be smaller than maxBufferSize/2
                    'fileReader',-1,...
                    'newBufferStart',-1,...
                    'newBufferEnd',-1,...
                    'ylim',[0,30000]);
    
    handles.datLoaded = 0;
    guidata(fig,handles);
    
    hideAllChildren(fig);
end

